"""empty message

Revision ID: 091be39d51b4
Revises: 8b5553b19cf3
Create Date: 2017-11-07 15:46:29.246244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091be39d51b4'
down_revision = '8b5553b19cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('course', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'course')
    # ### end Alembic commands ###
