"""empty message

Revision ID: 86cf285d94f9
Revises: 882678db7ec1
Create Date: 2017-11-17 09:02:58.147122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cf285d94f9'
down_revision = '882678db7ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('image', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'image')
    # ### end Alembic commands ###
