"""empty message

Revision ID: 882678db7ec1
Revises: 091be39d51b4
Create Date: 2017-11-14 08:57:04.121766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882678db7ec1'
down_revision = '091be39d51b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('user', sa.String(length=80), nullable=False))
    op.add_column('restaurant_name', sa.Column('user', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_name', 'user')
    op.drop_column('menu_items', 'user')
    # ### end Alembic commands ###
